# Generated by Django 5.2.6 on 2025-09-12 22:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZuluWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zulu_word', models.CharField(max_length=100)),
                ('english_translation', models.CharField(max_length=100)),
                ('pronunciation_guide', models.CharField(blank=True, max_length=100)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('greeting', 'Greeting'), ('farewell', 'Farewell'), ('phrase', 'Phrase')], max_length=50)),
                ('cultural_context', models.TextField(blank=True)),
                ('example_sentence_zulu', models.TextField(blank=True)),
                ('example_sentence_english', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('synonyms', models.ManyToManyField(blank=True, to='main_app.zuluword')),
            ],
        ),
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=255)),
                ('search_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('search_results', models.ManyToManyField(to='main_app.zuluword')),
            ],
        ),
        migrations.CreateModel(
            name='WordPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(default=1)),
                ('word1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word1_pair', to='main_app.zuluword')),
                ('word2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word2_pair', to='main_app.zuluword')),
            ],
            options={
                'unique_together': {('word1', 'word2')},
            },
        ),
        migrations.CreateModel(
            name='UserFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.zuluword')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
