# Generated by Django 5.2.6 on 2025-09-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zuluword',
            name='example_sentence_swati',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zuluword',
            name='swati_translation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
