# Generated by Django 5.2.6 on 2025-09-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_zuluword_example_sentence_swati_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zuluword',
            name='example_sentence_sotho',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zuluword',
            name='sotho_translation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
